contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #viralrecon channel"
    url: https://nfcore.slack.com/channels/viralrecon
    about: Discussion about the nf-core/viralrecon pipeline
